#Finish the same task as we did on Day 1, instead of using pipeline, let's do it from tokenizer to model, and analyze the vanilla output from scratch.

In [ ]:
!pip install datasets evaluate transformers[sentencepiece]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 365 kB 4.0 MB/s 
     |████████████████████████████████| 69 kB 5.5 MB/s 
     |████████████████████████████████| 4.9 MB 50.6 MB/s 
     |████████████████████████████████| 115 kB 52.7 MB/s 
     |████████████████████████████████| 120 kB 73.5 MB/s 
     |████████████████████████████████| 212 kB 64.3 MB/s 
     |████████████████████████████████| 127 kB 36.7 MB/s 
     |████████████████████████████████| 6.6 MB 51.2 MB/s 
     |████████████████████████████████| 1.3 MB 48.8 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [ ]:
from transformers import pipeline

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.


Moving 0 files to the new cache system


0it [00:00, ?it/s]

In [ ]:
classifier = pipeline("sentiment-analysis")
classifier("I've been waiting for a HuggingFace course my whole life.")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'label': 'POSITIVE', 'score': 0.9598049521446228}]

In [ ]:
Q1_text = "Eighteen years have gone by, and still I can bring back every detail of that day in the meadow. Washed clean of summer’s dust by days of gentle rain, the mountains wore a deep, brilliant green. The October breeze set white fronds of head-tall grasses swaying. One long streak of cloud hung pasted across a dome of frozen blue. It almost hurt to look at that faroff sky. A puff of wind swept across the meadow and through her hair before it slipped into the woods to rustle branches and send back snatches of distant barking-a hazy sound that seemed to reach us from the doorway to another world. We heard no other sounds. We met no other people. We saw only two bright, red birds leap startled from the center of the meadow and dart into the woods. As we ambled along, Naoko spoke to me of wells. Memory is a funny thing. When I was in the scene, I hardly paid it any mind. I never stopped to think of it as something that would make a lasting impression, certainly never imagined that eighteen years later I would recall it in such detail. I didn’t give a damn about the scenery that day. I was thinking about myself. I was thinking about the beautiful girl walking next to me. I was thinking about the two of us together, and then about myself again. It was the age, that time of life when every sight, every feeling, every thought came back, like a boomerang, to me. And worse, I was in love. Love with complications. Scenery was the last thing on my mind. Now, though, that meadow scene is the first thing that comes back to me. The smell of the grass, the faint chill of the wind, the line of the hills, the barking of a dog: these are the first things, and they come with absolute clarity. I feel as if I can reach out and trace them with a fingertip. And yet, as clear as the scene may be, no one is in it. No one. Naoko is not there, and neither am I. Where could we have disappeared to? How could such a thing have happened? Everything that seemed so important back then-Naoko, and the self I was then, and the world I had then: where could they have all gone? It’s true, I can’t even bring back Naoko’s face-not right away, at least. All I’m left holding is a background, sheer scenery, with no people up front."

In [ ]:
import nltk
from nltk import tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
Q1_sentence_nltk = tokenize.sent_tokenize(Q1_text)

In [ ]:
Q1_sentence_nltk

['Eighteen years have gone by, and still I can bring back every detail of that day in the meadow.',
 'Washed clean of summer’s dust by days of gentle rain, the mountains wore a deep, brilliant green.',
 'The October breeze set white fronds of head-tall grasses swaying.',
 'One long streak of cloud hung pasted across a dome of frozen blue.',
 'It almost hurt to look at that faroff sky.',
 'A puff of wind swept across the meadow and through her hair before it slipped into the woods to rustle branches and send back snatches of distant barking-a hazy sound that seemed to reach us from the doorway to another world.',
 'We heard no other sounds.',
 'We met no other people.',
 'We saw only two bright, red birds leap startled from the center of the meadow and dart into the woods.',
 'As we ambled along, Naoko spoke to me of wells.',
 'Memory is a funny thing.',
 'When I was in the scene, I hardly paid it any mind.',
 'I never stopped to think of it as something that would make a lasting impres

In [ ]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [ ]:
inputs = tokenizer(Q1_sentence_nltk, padding=True, truncation=True, return_tensors="pt")
print(inputs)

{'input_ids': tensor([[ 101, 7763, 2086,  ...,    0,    0,    0],
        [ 101, 8871, 4550,  ...,    0,    0,    0],
        [ 101, 1996, 2255,  ...,    0,    0,    0],
        ...,
        [ 101, 2673, 2008,  ...,    0,    0,    0],
        [ 101, 2009, 1521,  ...,    0,    0,    0],
        [ 101, 2035, 1045,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}


In [ ]:
inputs["input_ids"].shape

torch.Size([32, 48])

Why is it 32*48?

In [ ]:
print(max(Q1_sentence_nltk, key=len))
print(len(max(Q1_sentence_nltk, key=len).split(" ")))

A puff of wind swept across the meadow and through her hair before it slipped into the woods to rustle branches and send back snatches of distant barking-a hazy sound that seemed to reach us from the doorway to another world.
41


In [ ]:
max_sentence = "A puff of wind swept across the meadow and through her hair before it slipped into the woods to rustle branches and send back snatches of distant barking-a hazy sound that seemed to reach us from the doorway to another world."
tokens = tokenizer.tokenize(max_sentence)

print(tokens)
print(len(tokens))
max_input = tokenizer(max_sentence)
print(max_input)
print(len(max_input.input_ids))

['a', 'puff', 'of', 'wind', 'swept', 'across', 'the', 'meadow', 'and', 'through', 'her', 'hair', 'before', 'it', 'slipped', 'into', 'the', 'woods', 'to', 'rust', '##le', 'branches', 'and', 'send', 'back', 'snatch', '##es', 'of', 'distant', 'barking', '-', 'a', 'hazy', 'sound', 'that', 'seemed', 'to', 'reach', 'us', 'from', 'the', 'doorway', 'to', 'another', 'world', '.']
46
{'input_ids': [101, 1037, 23893, 1997, 3612, 7260, 2408, 1996, 13244, 1998, 2083, 2014, 2606, 2077, 2009, 5707, 2046, 1996, 5249, 2000, 18399, 2571, 5628, 1998, 4604, 2067, 23365, 2229, 1997, 6802, 19372, 1011, 1037, 26710, 2614, 2008, 2790, 2000, 3362, 2149, 2013, 1996, 7086, 2000, 2178, 2088, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
48


In [ ]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[1037,
 23893,
 1997,
 3612,
 7260,
 2408,
 1996,
 13244,
 1998,
 2083,
 2014,
 2606,
 2077,
 2009,
 5707,
 2046,
 1996,
 5249,
 2000,
 18399,
 2571,
 5628,
 1998,
 4604,
 2067,
 23365,
 2229,
 1997,
 6802,
 19372,
 1011,
 1037,
 26710,
 2614,
 2008,
 2790,
 2000,
 3362,
 2149,
 2013,
 1996,
 7086,
 2000,
 2178,
 2088,
 1012]

In [ ]:
print(tokenizer.decode(max_input["input_ids"]))
print(tokenizer.decode(ids))

[CLS] a puff of wind swept across the meadow and through her hair before it slipped into the woods to rustle branches and send back snatches of distant barking - a hazy sound that seemed to reach us from the doorway to another world. [SEP]
a puff of wind swept across the meadow and through her hair before it slipped into the woods to rustle branches and send back snatches of distant barking - a hazy sound that seemed to reach us from the doorway to another world.


In [ ]:
from transformers import AutoModel

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModel.from_pretrained(checkpoint)

Downloading:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['pre_classifier.weight', 'pre_classifier.bias', 'classifier.bias', 'classifier.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
outputs = model(**inputs)
print(outputs.last_hidden_state.shape)

In [ ]:
from transformers import AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**inputs)

In [ ]:
print(outputs.logits.shape)

torch.Size([32, 2])


In [ ]:
print(outputs.logits)

tensor([[-2.9097,  3.0603],
        [-2.9906,  3.1538],
        [-3.0856,  3.3513],
        [ 0.5252, -0.3588],
        [ 1.7268, -1.3978],
        [-0.1638,  0.2964],
        [ 2.4347, -1.9709],
        [-1.5700,  1.5212],
        [ 0.5479, -0.2465],
        [-3.0891,  3.2033],
        [-3.8900,  4.1634],
        [ 4.2343, -3.4772],
        [-3.5073,  3.6947],
        [ 3.6969, -3.0664],
        [-2.7650,  2.8711],
        [-3.7879,  4.0219],
        [-2.5296,  2.5948],
        [-3.1700,  3.3370],
        [ 2.3666, -1.9988],
        [-3.8532,  4.0928],
        [ 4.1809, -3.4629],
        [-2.3029,  2.3895],
        [-4.0548,  4.2781],
        [-1.8823,  1.9305],
        [ 3.0080, -2.4859],
        [ 2.7569, -2.3052],
        [ 3.5068, -2.8443],
        [ 3.2776, -2.6787],
        [ 3.4121, -2.7691],
        [ 2.0810, -1.6311],
        [-3.2181,  3.4149],
        [ 0.7319, -0.5070]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch

predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(predictions)

tensor([[2.5478e-03, 9.9745e-01],
        [2.1409e-03, 9.9786e-01],
        [1.5987e-03, 9.9840e-01],
        [7.0765e-01, 2.9235e-01],
        [9.5789e-01, 4.2105e-02],
        [3.8693e-01, 6.1307e-01],
        [9.8794e-01, 1.2061e-02],
        [4.3471e-02, 9.5653e-01],
        [6.8877e-01, 3.1123e-01],
        [1.8469e-03, 9.9815e-01],
        [3.1792e-04, 9.9968e-01],
        [9.9955e-01, 4.4744e-04],
        [7.4454e-04, 9.9926e-01],
        [9.9885e-01, 1.1541e-03],
        [3.5544e-03, 9.9645e-01],
        [4.0561e-04, 9.9959e-01],
        [5.9148e-03, 9.9409e-01],
        [1.4907e-03, 9.9851e-01],
        [9.8745e-01, 1.2550e-02],
        [3.5395e-04, 9.9965e-01],
        [9.9952e-01, 4.7879e-04],
        [9.0807e-03, 9.9092e-01],
        [2.4041e-04, 9.9976e-01],
        [2.1609e-02, 9.7839e-01],
        [9.9591e-01, 4.0950e-03],
        [9.9371e-01, 6.2927e-03],
        [9.9826e-01, 1.7418e-03],
        [9.9742e-01, 2.5827e-03],
        [9.9794e-01, 2.0636e-03],
        [9.761

In [ ]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

###How to get the predicted label for each sentence?

In [ ]:
pred_labels = torch.argmax(predictions, dim=1)
pred_labels

tensor([1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 1, 0])

In [ ]:
pred_labels = predictions.max(1).indices
print(pred_labels)

tensor([1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 1, 0])


### How to get the most positive and negative sentence in this paragraph?

In [ ]:
pred_labels = predictions.max(0).indices
print(pred_labels)
print(Q1_sentence_nltk[int(pred_labels[0])])
print(Q1_sentence_nltk[int(pred_labels[1])])

tensor([11, 22])
When I was in the scene, I hardly paid it any mind.
The smell of the grass, the faint chill of the wind, the line of the hills, the barking of a dog: these are the first things, and they come with absolute clarity.


In [ ]:
most_score = predictions.max(0)
most_score

torch.return_types.max(
values=tensor([0.9996, 0.9998], grad_fn=<MaxBackward0>),
indices=tensor([11, 22]))

In [ ]:
Q1_result = classifier(Q1_sentence_nltk)

In [ ]:
positive_most_score = 0
positive_most_sent = ''
negative_most_score = 0
negative_most_sent = ''
for i in range(len(Q1_sentence_nltk)):
  current_result = Q1_result[i]
  current_label = current_result["label"]
  current_score = current_result["score"]
  current_sentence = Q1_sentence_nltk[i]
  print(current_label,current_score,current_sentence)
  if current_label == "POSITIVE":
    if current_score >  positive_most_score:
      positive_most_sent = current_sentence
      positive_most_score = current_score
  if current_label == "NEGATIVE":
    if current_score >  negative_most_score:
      negative_most_sent = current_sentence
      negative_most_score = current_score 
print("positive_most_sent: ", positive_most_sent) 
print("positive score: ", positive_most_score)
print("negative_most_sent: ", negative_most_sent)
print("negative score: ", negative_most_score)


POSITIVE 0.9974521994590759 Eighteen years have gone by, and still I can bring back every detail of that day in the meadow.
POSITIVE 0.9978590607643127 Washed clean of summer’s dust by days of gentle rain, the mountains wore a deep, brilliant green.
POSITIVE 0.9984012246131897 The October breeze set white fronds of head-tall grasses swaying.
NEGATIVE 0.7076473832130432 One long streak of cloud hung pasted across a dome of frozen blue.
NEGATIVE 0.957894504070282 It almost hurt to look at that faroff sky.
POSITIVE 0.6130686402320862 A puff of wind swept across the meadow and through her hair before it slipped into the woods to rustle branches and send back snatches of distant barking-a hazy sound that seemed to reach us from the doorway to another world.
NEGATIVE 0.9879387617111206 We heard no other sounds.
POSITIVE 0.9565290808677673 We met no other people.
NEGATIVE 0.6887699961662292 We saw only two bright, red birds leap startled from the center of the meadow and dart into the woods.


#Finish the same task as **above**, instead of using the tokenizer directly, do tokenize, convert tokens into token_ids, add start and end token, do padding and generate attention mask by your own.

## What should we do to process a single sentence?

In [ ]:
tokens_sent1 = tokenizer.tokenize(Q1_sentence_nltk[0])
  # output = tokenizer(sent)

print(tokens_sent1)
print(len(tokens_sent1))
# print(output)

['eighteen', 'years', 'have', 'gone', 'by', ',', 'and', 'still', 'i', 'can', 'bring', 'back', 'every', 'detail', 'of', 'that', 'day', 'in', 'the', 'meadow', '.']
21


In [ ]:
ids_sent1 = tokenizer.convert_tokens_to_ids(tokens_sent1)
ids_sent1

[7763,
 2086,
 2031,
 2908,
 2011,
 1010,
 1998,
 2145,
 1045,
 2064,
 3288,
 2067,
 2296,
 6987,
 1997,
 2008,
 2154,
 1999,
 1996,
 13244,
 1012]

In [ ]:
print(tokenizer.cls_token_id)
print(tokenizer.sep_token_id)

101
102


In [ ]:
editted_token_ids_sent1 = torch.tensor([tokenizer.cls_token_id] + ids_sent1 + [tokenizer.sep_token_id])
editted_token_ids_sent1

tensor([  101,  7763,  2086,  2031,  2908,  2011,  1010,  1998,  2145,  1045,
         2064,  3288,  2067,  2296,  6987,  1997,  2008,  2154,  1999,  1996,
        13244,  1012,   102])

In [ ]:
model(editted_token_ids_sent1)

IndexError: ignored

The problem is that we sent a single sequence to the model, whereas 🤗 Transformers models expect multiple sentences by default. 

In [ ]:
editted_multi_d_token_ids_sent1 = torch.tensor([[tokenizer.cls_token_id] + ids_sent1 + [tokenizer.sep_token_id]])
model(editted_multi_d_token_ids_sent1)

SequenceClassifierOutput(loss=None, logits=tensor([[-2.9097,  3.0603]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

## What about processing multiple sentences at one time?

In [ ]:
tokens_sent2 = tokenizer.tokenize(Q1_sentence_nltk[1])
  # output = tokenizer(sent)

print(tokens_sent2)
print(len(tokens_sent2))
# print(output)

['washed', 'clean', 'of', 'summer', '’', 's', 'dust', 'by', 'days', 'of', 'gentle', 'rain', ',', 'the', 'mountains', 'wore', 'a', 'deep', ',', 'brilliant', 'green', '.']
22


In [ ]:
ids_sent2 = tokenizer.convert_tokens_to_ids(tokens_sent2)
ids_sent2

[8871,
 4550,
 1997,
 2621,
 1521,
 1055,
 6497,
 2011,
 2420,
 1997,
 7132,
 4542,
 1010,
 1996,
 4020,
 5078,
 1037,
 2784,
 1010,
 8235,
 2665,
 1012]

In [ ]:
print(tokenizer.cls_token_id)
print(tokenizer.sep_token_id)

101
102


In [ ]:
editted_multi_d_token_ids_sent2 = torch.tensor([[tokenizer.cls_token_id] + ids_sent2 + [tokenizer.sep_token_id]])
editted_multi_d_token_ids_sent2

tensor([[ 101, 8871, 4550, 1997, 2621, 1521, 1055, 6497, 2011, 2420, 1997, 7132,
         4542, 1010, 1996, 4020, 5078, 1037, 2784, 1010, 8235, 2665, 1012,  102]])

In [ ]:
print(editted_multi_d_token_ids_sent1.shape)
print(editted_multi_d_token_ids_sent2.shape)

torch.Size([1, 23])
torch.Size([1, 24])


## Padding to generate rectangular shape!!!

In order to work around this, we’ll use padding to make our tensors have a rectangular shape. Padding makes sure all our sentences have the same length by adding a special word called the padding token to the sentences with fewer values. For example, if you have 10 sentences with 10 words and 1 sentence with 20 words, padding will ensure all the sentences have 20 words.


The padding token ID can be found in tokenizer.pad_token_id. 


In our example, the resulting tensor looks like this:

In [ ]:
tokenizer.pad_token_id

0

In [ ]:
padded_editted_multi_d_token_ids_sent1 = torch.tensor([[tokenizer.cls_token_id] + ids_sent1 + [tokenizer.sep_token_id] + [tokenizer.pad_token_id]])
padded_editted_multi_d_token_ids_sent1

tensor([[  101,  7763,  2086,  2031,  2908,  2011,  1010,  1998,  2145,  1045,
          2064,  3288,  2067,  2296,  6987,  1997,  2008,  2154,  1999,  1996,
         13244,  1012,   102,     0]])

In [ ]:
padded_inputs_ids = torch.stack((padded_editted_multi_d_token_ids_sent1.squeeze(),editted_multi_d_token_ids_sent2.squeeze()))
padded_inputs_ids

tensor([[  101,  7763,  2086,  2031,  2908,  2011,  1010,  1998,  2145,  1045,
          2064,  3288,  2067,  2296,  6987,  1997,  2008,  2154,  1999,  1996,
         13244,  1012,   102,     0],
        [  101,  8871,  4550,  1997,  2621,  1521,  1055,  6497,  2011,  2420,
          1997,  7132,  4542,  1010,  1996,  4020,  5078,  1037,  2784,  1010,
          8235,  2665,  1012,   102]])

In [ ]:
model(editted_multi_d_token_ids_sent1).logits

tensor([[-2.9097,  3.0603]], grad_fn=<AddmmBackward0>)

In [ ]:
model(editted_multi_d_token_ids_sent2).logits

tensor([[-2.9906,  3.1538]], grad_fn=<AddmmBackward0>)

In [ ]:
model(padded_inputs_ids).logits

tensor([[-2.7389,  2.8820],
        [-2.9906,  3.1538]], grad_fn=<AddmmBackward0>)

There’s something wrong with the logits in our batched predictions: the first row should be the same as the logits for the first sentence, but we’ve got completely different values!

This is because the key feature of Transformer models is attention layers that contextualize each token. These will take into account the padding tokens since they attend to all of the tokens of a sequence. To get the same result when passing individual sentences of different lengths through the model or when passing a batch with the same sentences and padding applied, we need to tell those attention layers to ignore the padding tokens. This is done by using an attention mask.

## Generate attention mask!

In [ ]:
attention_mask_sent1_2 = torch.ones(padded_inputs_ids.shape)
attention_mask_sent1_2

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1.]])

In [ ]:
attention_mask_sent1_2[0,-1] = 0
attention_mask_sent1_2

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1.]])

In [ ]:
model(torch.tensor(padded_inputs_ids), attention_mask=torch.tensor(attention_mask_sent1_2)).logits

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor([[-2.9097,  3.0603],
        [-2.9906,  3.1538]], grad_fn=<AddmmBackward0>)

## Now try to process the whole paragraph at once!